# Custom Language File for Launcher Customizer

[ejs.app]
title = "Noxenth Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/Neckyyyy/NoxenthLauncher"
mediaYouTubeURL = "https://www.youtube.com/@Noxenth"
mediaDiscordURL = "https://discord.gg/USeACgVSPV"

[ejs.settings]
sourceGithubLink = "https://github.com/Neckyyyy/NoxenthLauncher"
supportLink = "https://github.com/Neckyyyy/NoxenthLauncher/issues"

[ejs.welcome]
welcomeHeader = "Добро пожаловать на Noxenth!"
welcomeDescription = "Реализуйте свои инженерные и строительные проекты с помощью продвинутых технологий мода Create, Mekanism и других."
welcomeDescCTA = "Вы в нескольких кликах от входа в этот мир."
