# Custom Language File for Launcher Customizer

[ejs.app]
title = "Compass Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/notnq2gre/CompassLauncher"
mediaYouTubeURL = "https://www.youtube.com/"
mediaDiscordURL = "https://discord.gg/GU2UMhwZ"

[ejs.settings]
sourceGithubLink = "https://github.com/notnq2gre/CompassLauncher"
supportLink = "https://github.com/notnq2gre/CompassLauncher/issues"

[ejs.welcome]
welcomeHeader = "Добро пожаловать в мир Compass!"
welcomeDescription = "Реализуйте свои инженерные и строительные проекты с помощью продвинутых технологий различных модов в увлекательных режимах."
welcomeDescCTA = "Вы в нескольких кликах от входа."
